---
apiVersion: v1
kind: Namespace
metadata:
  name: game2048
---
apiVersion: v1
kind: Service
metadata:
  namespace: game2048
  name: game2048
  annotations:
    remotekube/service-port: "80"
    remotekube/service-protocol: "TCP"
spec:
  selector:
    app: game2048
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game2048
  name: game2048
  labels:
    app: game2048
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game2048
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: game2048
    spec:
      containers:
        - name: game2048
          image: alexwhen/docker-2048:latest
          imagePullPolicy: IfNotPresent
