---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: v1
kind: Service
metadata:
  namespace: minecraft
  name: minecraft
  annotations:
    remotekube/service-port: "25565"
    remotekube/service-protocol: "TCP"
spec:
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
---
apiVersion: v1
kind: Pod
metadata:
  namespace: minecraft
  name: minecraft
  labels:
    app: minecraft
spec:
  containers:
  - name: minecraft
    image: itzg/minecraft-server:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: EULA
      value: "TRUE"
