---
apiVersion: v1
kind: Namespace
metadata:
  name: remotekube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remotekube
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create","list","update","delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create","list","update","delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: remotekube
  name: remotekube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: remotekube
  name: remotekube
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: remotekube
subjects:
  - kind: ServiceAccount
    name: remotekube
    namespace: remotekube
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: remotekube
  namespace: remotekube
data:
  LOGLEVEL: INFO
  REMOTEKUBE_NAMESPACES: minecraft,game2048
  REMOTEKUBE_CONFIGMAP_NAME: remotekube-registration-code
  R3_ACCESS_KEY_ID: PUT_YOUR_KEY_ID_HERE
  R3_SECRET_ACCESS_KEY: PUT_YOUR_SECRET_HERE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: remotekube
  name: remotekube
  labels:
    app: remotekube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remotekube
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: remotekube
    spec:
      serviceAccountName: remotekube
      containers:
        - name: remotekube
          image: ryotayaguchi/remotekube:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: remotekube
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
